# Basics of PyTorch

In [ ]:
import torch
import numpy as np

print('PyTorch version:', torch.__version__)

np.set_printoptions(precision=3)

PyTorch version: 2.5.1+cu121

### Creating tensors in PyTorch

In [ ]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)

In [ ]:
torch.is_tensor(a), torch.is_tensor(t_a)

(False, True)

In [ ]:
t_ones = torch.ones(2, 3)

t_ones.shape

torch.Size([2, 3])

In [ ]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
rand_tensor = torch.rand(2,3)

print(rand_tensor)

tensor([[0.4145, 0.2000, 0.2532],
        [0.4464, 0.3425, 0.0846]])

### Manipulating the data type and shape of a tensor

In [ ]:
t_a_new = t_a.to(torch.int64)

print(t_a_new.dtype)

torch.int64

In [ ]:
t = torch.rand(3, 5)

t_tr = torch.transpose(t, 0, 1) #dimensions to be transposed are 0 and 1
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])

In [ ]:
t = torch.rand(3, 5, 7)

t_tr = torch.transpose(t, 0, 1) #dimensions to be transposed are 0 and 1
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5, 7])  -->  torch.Size([5, 3, 7])

In [ ]:
t = torch.zeros(30)

t_reshape = t.reshape(5, 6)

print(t_reshape.shape)

torch.Size([5, 6])

### Applying mathematical operations to tensors

In [ ]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [ ]:
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [ ]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])

In [ ]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))

print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])

In [ ]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)

print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])

In [ ]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)

print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

In [ ]:
np.sqrt(np.sum(np.square(t1.numpy()), axis=1))

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)

# Automatic differentiation

In [ ]:
x = torch.tensor([1.7],dtype=torch.float32)
w = torch.tensor([4.2],dtype=torch.float32, requires_grad=True)

def model(w, x):
  return w * w * x

y = model(w, x)

y.backward()

print(y)
print(w.grad)

tensor([29.9880], grad_fn=<MulBackward0>)
tensor([14.2800])

### Always use `torch.no_grad()` when evaluating a model to avoid corrupting the gradients

In [ ]:
new_data = torch.tensor([2.7],dtype=torch.float32)

with torch.no_grad():
  y = model(w, new_data)

print(y)
print(w.grad)

tensor([47.6280])
tensor([14.2800])

## Dataloader in PyTorch

In [ ]:
# Load molecular solvation data
import pandas as pd

df = pd.read_csv('solubility_data.csv')

df.head(10)

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
0,Amigdalin,-0.974,1,457.432,7,3,7,202.32,-0.77,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1,Fenfuram,-2.885,1,201.225,1,2,2,42.24,-3.30,Cc1occc1C(=O)Nc2ccccc2
2,citral,-2.579,1,152.237,0,0,4,17.07,-2.06,CC(C)=CCCC(C)=CC(=O)
3,Picene,-6.618,2,278.354,0,5,0,0.00,-7.87,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43
4,Thiophene,-2.232,2,84.143,0,1,0,0.00,-1.33,c1ccsc1
5,benzothiazole,-2.733,2,135.191,0,2,0,12.89,-1.50,c2ccc1scnc1c2
6,"2,2,4,6,6'-PCB",-6.545,1,326.437,0,2,1,0.00,-7.32,Clc1cc(Cl)c(c(Cl)c1)c2c(Cl)cccc2Cl
7,Estradiol,-4.138,1,272.388,2,4,0,40.46,-5.03,CC12CCC3C(CCc4cc(O)ccc34)C2CCC1O
8,Dieldrin,-4.533,1,380.913,0,5,0,12.53,-6.29,ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl
9,Rotenone,-5.246,1,394.423,0,5,3,63.22,-4.42,COc5cc4OCC3Oc2c1CC(Oc1ccc2C(=O)C3c4cc5OC)C(C)=C

In [ ]:


X = df[['Molecular Weight','Polar Surface Area']]
X.head()

   Molecular Weight  Polar Surface Area
0           457.432              202.32
1           201.225               42.24
2           152.237               17.07
3           278.354                0.00
4            84.143                0.00

In [ ]:
from torch.utils.data import DataLoader, TensorDataset

# Convert DataFrame to a NumPy array and then to a PyTorch Tensor
tensor = torch.tensor(X.values[:10])

# Create a TensorDataset and DataLoader
dataset = TensorDataset(tensor)
dataloader = DataLoader(dataset, batch_size=5, shuffle=True)

for batch in dataloader:
    print(batch)

[tensor([[201.2250,  42.2400],
        [272.3880,  40.4600],
        [394.4230,  63.2200],
        [152.2370,  17.0700],
        [278.3540,   0.0000]], dtype=torch.float64)]
[tensor([[457.4320, 202.3200],
        [ 84.1430,   0.0000],
        [380.9130,  12.5300],
        [326.4370,   0.0000],
        [135.1910,  12.8900]], dtype=torch.float64)]